# Server configurations
server:
  name: test
  environment: development
  addresses:
    application:
      host: 0.0.0.0
      port: 80
    monitoring:
      host: 0.0.0.0
      port: 8080
  version: dev
# Monitoring configurations
monitoring:
  prometheus:
    enabled: true
tracing:
  otel:
    enabled: true